server:
  port: ${SERVER_PORT:9060}
spring:
  application:
    name: notificacoes
  profiles:
    active: default

---
spring:
  config:
    activate:
      on-profile: default

  kafka:
    bootstrap-servers: kafka:9092
    topic:
      evento-informar-paciente-consulta: evento-informar-paciente-consulta
    consumer:
      group-id: grupo-notificacoes
      auto-offset-reset: earliest # Ou latest, dependendo do caso de uso - earliest lê desde o início do tópico
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*" # Asterisco para confiar em todos os pacotes para deserializacao
        spring.json.add.type.headers: false # Opcional: Evita headers de tipo para simplicidade

  mail:
    host: smtp.gmail.com
    port: 587
    username: dev.juniorsmartins@gmail.com
    password: ljiz cypm zghp wxnw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
